# Default values for soveren-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


receiver:
  daemonSetAnnotations: {}
  daemonSetLabels: {}
  podAnnotations: {}
  image:
    name: soveren/receiver
    tag: latest
    pullPolicy: Always
  podLabels: {}
  resources:
    requests:
      cpu: "20m"
      memory: "64Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
  priorityClassName: ""
  env: []
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  service:
    annotations: { }
    labels: { }
    port: 80
    targetPort: 8080


sender:
  daemonSetAnnotations: {}
  daemonSetLabels: {}
  podAnnotations: {}
  image:
    name: soveren/sender
    tag: latest
    pullPolicy: Always
  podLabels: {"soveren-test"}
  resources:
    requests:
      cpu: "20m"
      memory: "64Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
  priorityClassName: ""
  env:
    - name: URLS
      value: "http://receiver:8081,http://satellite:8082"
    - name: TIMEOUT
      value: "60"
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  service:
    annotations: { }
    labels: { }
    port: 8080

satellite:
  daemonSetAnnotations: {}
  daemonSetLabels: {}
  podAnnotations: {}
  image:
    name: soveren/satellite
    tag: latest
    pullPolicy: Always
  podLabels: {}
  resources:
    requests:
      cpu: "20m"
      memory: "64Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
  priorityClassName: ""
  env: []
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  service:
    annotations: { }
    labels: { }
    port: 80
    targetPort: 8080