apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-receiver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: receiver
          image: {{ .Values.receiver.image.name }}:{{ .Values.receiver.image.tag }}
          ports:
            - containerPort: 8080