apiVersion: v1
kind: Service
metadata:
  name: satellite
spec:
  selector:
    app: {{ .Chart.Name }}-satellite
  ports:
    - name: http
      port: {{ .Values.receiver.service.port }}
      targetPort: {{ .Values.satellite.service.targetPort }}