apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-satellite
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-satellite
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-satellite
    spec:
      containers:
        - name: satellite
          image: {{ .Values.satellite.image.name }}:{{ .Values.satellite.image.tag }}
          ports:
            - containerPort: 8080