apiVersion: v1
kind: Service
metadata:
  name: slave
spec:
  selector:
    app: {{ .Chart.Name }}-slave
  ports:
    - name: http
      port: {{ .Values.receiver.service.port }}
      targetPort: {{ .Values.receiver.service.targetPort }}