apiVersion: v1
kind: Service
metadata:
  name: slave
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Values.slave.image.name }}
  ports:
    - name: http
      port: {{ .Values.receiver.service.port }}
      targetPort: {{ .Values.slave.service.targetPort }}